# Generated by Django 5.2.5 on 2025-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRapat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tanggal', models.DateField()),
                ('jam', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('judul_kontrak', models.CharField(blank=True, max_length=100, null=True)),
                ('kas_masuk', models.IntegerField(default=0)),
                ('kas_keluar', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Artikel',
            },
        ),
    ]
