# Generated by Django 5.2.5 on 2025-08-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarapat',
            options={'verbose_name_plural': 'judul_kontrak'},
        ),
        migrations.AlterField(
            model_name='datarapat',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
