# Generated by Django 5.2.5 on 2025-08-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0002_alter_datarapat_options_alter_datarapat_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRapatDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tanggal', models.DateTimeField()),
                ('jam', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('judul_kontrak', models.CharField(blank=True, max_length=100, null=True)),
                ('kas_masuk', models.IntegerField(default=0)),
                ('kas_keluar', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'judul_kontrak',
            },
        ),
        migrations.DeleteModel(
            name='DataRapat',
        ),
    ]
