# Generated by Django 5.2.5 on 2025-08-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0003_datarapatdb_delete_datarapat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarapatdb',
            options={'verbose_name_plural': 'Kontrak'},
        ),
        migrations.AddField(
            model_name='datarapatdb',
            name='id_nama_anggota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
