# Generated by Django 5.2.5 on 2025-08-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0004_alter_datarapatdb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarapatdb',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
