# Generated by Django 5.2.5 on 2025-08-19 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0005_alter_datarapatdb_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarapatdb',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
