# Generated by Django 5.2.5 on 2025-08-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0006_alter_datarapatdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarapatdb',
            name='id_random',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
