# Generated by Django 5.2.5 on 2025-08-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rapat', '0007_datarapatdb_id_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarapatdb',
            name='id_random',
        ),
        migrations.AlterField(
            model_name='datarapatdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='datarapatdb',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
