# Generated by Django 5.2.5 on 2025-08-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamaDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'nama',
            },
        ),
    ]
